### ISSUE TITLE
index 33 is out of bounds for dimension 0 with size 33

### ISSUE THREAD

**Issue by GabrielLin** [sshailabh/SemEval-2021-Task-11#2]
When I run `Sub-task-B.ipynb`, there is an issue at `self.transitions[tags[i + 1], tags[i]] + feat[tags[i + 1]]` at `_score_sentence` function of `BiLSTM_CRF` class. Could you help?  Thanks.

**Comment by sshailabh** [comment]
Sorry, I did not reply to your previous mail. Due to the second wave of
covid-19, I am unable to look into the code right now. Could you wait till
20 May or you need it urgently?

Regards,
Shashank

**Comment by GabrielLin** [comment]
@sshailabh , thank you for your response. Sure, I will wait for you. Thanks.

**Comment by GabrielLin** [comment]
Sorry. I did not be notified of the update of the repo.

The issues have been fixed by the author in the latest version. Thank you @sshailabh .
